Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
    path('users/',include('users.urls')),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

pizzas/urls.py
from django.urls import path
#the path function is needed to map URLS to views

from . import views 
#tells python to import the views.py file 
#from the same directory as theh urls.py file
#we just created

app_name = 'pizzas'
#helps django distinguish this url file from the
#project url file

urlpatterns = [
    path('',views.index, name='index'),
    #path is the map
    #the empty '' is the base url
    #calls index function in views.py
    #provides name index for the url later
    #index is the home page
    path('pizzas',views.pizzas,name='pizzas'),
    #this is the url to list all the available pizzas 
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    #this is the url to each individual pizza by their id#
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),
]

#url patterns is a list of individual pages

users/urls.py
from django.urls import path, include

from . import views #write our own view for registration

app_name = 'users'

urlpatterns = [
    #include default urls 
    path('',include('django.contrib.auth.urls')),
    #registration page
    path('register/', views.register, name='register'), #use django's form, but we create our own view and template
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
        #this is a string method
        #this returns the class Pizza's attribute name
        #returns something useful instead of garbage

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    #makes a connection, 1 pizza can have many toppings
    name = models.CharField(max_length=200)
    #we do not need a textbox but a character box 

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    #makes a connection, 1 pizza can have many toppings
    text = models.TextField()
    #to add an attribute, first you create the attribute
    #then you save the file
    #then you make a migration
    #then make sure your view is correct for the html
    #add it to the html
    date_added = models.DateTimeField(auto_now_add=True)
   

    def __str__(self):
        return f"{self.text[:100]}..."

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta: #a meta class defines the behavior of PizzaForm
        model = Comment
        fields = ['text']
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.

#when a URL request matches the url pattern in urls.py
#it looks for the function called index() in the views.py file

def index(request):
    #this is where the url request is processed
    return render(request, 'pizzas/index.html')
    #this sends the requesr back to the browser using an html template
    #that defines what the page will look like

from .models import Pizza, Comment

def pizzas(request):
    pizzas = Pizza.objects.all()
    #get all the pizza objects, Hawaiian and Meat Lovers

    context = {'pizzas':pizzas}
    #define the data we will pass to the skeleton html

    return render(request, 'pizzas/pizzas.html', context)
    #return the get request, send it to pizzas/pizzas.html
    #with the data of the available pizzas


def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    #get the object associated with the id we requested
    toppings = pizza.topping_set.all()
    #access the foreign key by the entry_set function
    #list them all
    comment = pizza.comment_set.all()
    context = {'pizza':pizza, 'toppings':toppings, 'comments': comment} #red is variable for html site

    return render(request, 'pizzas/pizza.html', context)

from .forms import CommentForm

@login_required
def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    #get the pizza we requested

    if request.method != 'POST': 
        #if the request is a 'GET' request
        form = CommentForm() 
        #create a form, then render the request to the html page
    else: 
        #if it is a post request
        form = CommentForm(data=request.POST) 
        #post the request

        if form.is_valid():
            #if the form doesn't have errors
            comment = form.save(commit=False)
            #don't save the object to the database yet until we've assigned
            #the new comment to the pizza page
            comment.pizza = pizza
            comment.owner = request.user
            #assign the new comment to the puser
            comment.save()
            #save the comment
            return redirect('pizzas:pizza', pizza_id=pizza_id)
            #redirect the user back to the previous page associated with the id

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html', context)

users/views.py
# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth import login
from  django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):

    if request.method != 'POST':
        form = UserCreationForm() #form made by django to create users
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            #new user is now an object
            new_user = form.save()
            #log the user in and redirect them to the home page
            login(request, new_user)
            return redirect('pizzas:index')

    context = {'form':form}

    return render(request, 'registration/register.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a>
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
    {% if user.is_authenticated %}

    Hello, {{user.username}}!
        <a href="{% url 'users:logout' %}">Log out</a>

    {% else %}

        <a href="{% url 'users:login' %}">Log in</a>
        <a href="{% url 'users:register' %}">Register</a>
    {% endif %}
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% load static %}

{% block content %}

<p>Welcome to the Pizzeria Homepage!</p>

<p>This website helps you keep track of your pizzas, 
    and any topping that comes with them.</p>

<img src="{% static 'pizzas/images/index_photo.jpg' %}">

{% endblock content %}
    <!-- index.html is the child template that will inherit all elements and then extend
    elements from the base.html page (the parent template), which includes hyperlinks and 
    and then the content of the index.html between the block and endblock contents-->

pizzas/templates/pizzas/new_comment.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Add a new comment:</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}

<button name="submit">Save comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% load static %}

{% block content %}

<p>Pizza: {{pizza}}</p>

<ul>
    {% for topping in toppings %}

    <li>{{ topping.name }}</li> 

    {% empty %}

    <li>There are no toppings for this pizza yet.</li>

    {% endfor %}
</ul>

<img src="{% static 'pizzas/images/pizza_html_photo.jpg' %}">

<p>Comments: </p>

<ul>
    {% for comment in comments %}
    <li>{{comment.owner}} at {{comment.date_added|date:'M d, Y H:i'}} said:</li>
    <p>{{ comment.text }}<p>
    <br>

    {% empty %}
    <li>There are no comments for this pizza yet.</li>

    {% endfor %}

</ul>

<p>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>
</p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% load static %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}

    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </li> 

    {% empty %}

    <li>No pizzas have been added yet.</li>

    {% endfor %}
</ul>

<img src="{% static 'pizzas/images/pizzas_html_photo.jpg' %}">

{% endblock content %}

<!-- <ul> a bulleted list in HTML is called an unordered list
<li> li is a list item 
{{print}} double braces prints a variable
HTML needs an endfor tag to end the for loop -->